openapi: 3.0.0
info:
  title: WorkPod API
  description: API for managing workpod bookings and access
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Development server

components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
          enum: [PENDING, CONFIRMED, FAILED, CANCELLED]
        totalAmount:
          type: number
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        error:
          type: string
    StandardResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
        error:
          $ref: '#/components/schemas/Error'

  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /auth:
    post:
      summary: Authenticate user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      token:
                        type: string
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'

  /pods:
    get:
      summary: List available pods
      tags: [Pods]
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: latitude
          schema:
            type: number
        - in: query
          name: longitude
          schema:
            type: number
      responses:
        200:
          description: List of nearby pods
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      pods:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              format: uuid
                            name:
                              type: string
                            status:
                              type: string
                              enum: [AVAILABLE, OCCUPIED, MAINTENANCE]
                            hourlyRate:
                              type: number
                            location:
                              type: object
                              properties:
                                latitude:
                                  type: number
                                longitude:
                                  type: number
                                address:
                                  type: string
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'

  /bookings:
    post:
      summary: Create a booking
      tags: [Bookings]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                podId:
                  type: string
                  format: uuid
                startTime:
                  type: string
                  format: date-time
                endTime:
                  type: string
                  format: date-time
      responses:
        201:
          description: Booking created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      booking:
                        $ref: '#/components/schemas/Booking'
                      clientSecret:
                        type: string
                        description: Stripe payment intent client secret
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        409:
          description: Pod not available
          $ref: '#/components/responses/Error' 